keys:
  - &primary age1kmyypm3zq50ul5wrswxwp669jm7nt56z9kpc2d5awtv2etwzzpmqr6fr5k
  - &core age1w7gfrlckwurlrmjdmy4jst472wkvrrdffmycrr853cak68hfjsss8lrnjw
  - &services0 age1kllehtqjxl802lew2zd8lwn5emxewdd4p9aq9zaaykln8rkp2gaq7057ln

creation_rules:

  - path_regex: keys/hosts/core_.*
    key_groups:
      - age:
        - *primary
        - *core

  - path_regex: keys/hosts/services0_.*
    key_groups:
      - age:
        - *primary
        - *services0

  - path_regex: keys/pdns-
    key_groups:
      - age:
        - *primary
        - *services0
  - path_regex: keys/acme-credentials$
    key_groups:
      - age:
        - *primary
        - *core
        - *services0
  - path_regex: keys/vaultwarden-
    key_groups:
      - age:
        - *primary
        - *services0
  - path_regex: keys/backup-passphrase
    key_groups:
      - age:
        - *primary
        - *core
        - *services0
  - path_regex: keys/mailcore-
    key_groups:
      - age:
        - *primary
        - *core

  # Fallback just uses the primary
  - key_groups:
      - age:
          - *primary
